# Generated by Django 2.0.5 on 2018-06-12 00:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text="Enter the question here! LaTeX formatting is accepted... It's just going to be turned into LaTeX anyways!", unique=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1 (Easy)'), (2, '2 (Moderate)'), (3, '3 (Difficult)')], default=1)),
                ('index', models.PositiveSmallIntegerField(blank=True, default=50, help_text="I'm not really sure why this is needed...", null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('book', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='course', chained_model_field='course', help_text='Select a book from above.', null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Book')),
                ('chapter', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='book', chained_model_field='book', help_text='Select a chapter from above.', null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Course')),
                ('objective', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='chapter', chained_model_field='chapter', help_text='(REQUIRED) Select an objective.', on_delete=django.db.models.deletion.PROTECT, to='questions.Objective')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Source')),
            ],
            options={
                'verbose_name': 'question block',
                'verbose_name_plural': 'question blocks',
            },
        ),
        migrations.CreateModel(
            name='QuestionBlockQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_question_text', models.TextField(help_text="Enter the question here! LaTeX formatting is accepted... It's just going to be turned into LaTeX anyways!", unique=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1 (Easy)'), (2, '2 (Moderate)'), (3, '3 (Difficult)')], default=1)),
                ('index', models.PositiveSmallIntegerField(blank=True, default=50, help_text="I'm not really sure why this is needed...", null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('master_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.QuestionBlock')),
            ],
            options={
                'verbose_name': 'question block question',
                'verbose_name_plural': 'question block questions',
            },
        ),
    ]
